sudo: required

language: csharp
cache:
  directories:
  - packages

services:
  - docker

before_install:
- docker build -t webapp:test .
- docker run -it -v packages:/root/.nuget/packages -p 5000:5000 webapp:test